d569bd3a38fb60a14d1f8cc20a07b920  -15 current  2024-08-24 14:50:10  24.05.4169.797f7dc49e0b  6.6.46                          *

diff --git a/home-manager/_scripts/.scripts/gt-conn b/home-manager/_scripts/.scripts/gt-conn
--- a/home-manager/_scripts/.scripts/gt-conn
+++ b/home-manager/_scripts/.scripts/gt-conn
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
 
-# Prompt for VPN password
-read -s -p "Enter your VPN password: " vpn_password
-echo
-
-# Define other connection parameters
 username="cmiller427"
 twofactor="push1"
 gateway="DC Gateway"
 protocol="gp"
 server="vpn.gatech.edu"
 
-# Connect to VPN
+# Fetch the password from Bitwarden
+vpn_password=$(bw list items --search "Georgia Tech" | jq -r '.[0].login.password')
+if [ -z "$vpn_password" ]; then
+  echo "Error: Password not found in Bitwarden."
+  exit 1
+fi
+
 echo -e "$vpn_password\n$twofactor\n$gateway" | sudo openconnect --protocol=$protocol --user=$username --passwd-on-stdin $server
